### ISSUE TITLE
Can't work correctly in ItemsControl

### ISSUE THREAD

**Issue by sunday9th** [JaykeBird/ssui#2]
```C#
<ItemsControl ItemsSource="{Binding Strs}" >
    <ItemsControl.ItemTemplate>
        <DataTemplate>
            <ssui:DoubleSpinner Height="60" Value="1000" />
        </DataTemplate>
    </ItemsControl.ItemTemplate>
</ItemsControl>
```
my code above, but what i get (and Height attr is not work at the same time)
![image](https://user-images.githubusercontent.com/1252279/127078232-2e4e2ac0-187a-45c3-97ad-2d89fc56095e.png)

**Comment by sunday9th** [comment]
vs2019 & .net framework 4.7.2

**Comment by JaykeBird** [comment]
We're working on this in #3 now!
